
# Gem::Specification for Shoulda-generators-0.1.0
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: shoulda-generators
version: !ruby/object:Gem::Version 
  version: 0.1.0
platform: ruby
authors: 
- Josh Nichols
autorequire: 
bindir: bin

date: 2008-07-01 00:00:00 -04:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: Generators which create tests using shoulda
email: josh@technicalpickles.com
executables: []

extensions: []

extra_rdoc_files: 
- README.markdown
files: 
- Manifest
- rails_generators/shoulda_haml_scaffold/shoulda_haml_scaffold_generator.rb
- rails_generators/shoulda_haml_scaffold/templates/blueprint/ie.css
- rails_generators/shoulda_haml_scaffold/templates/blueprint/print.css
- rails_generators/shoulda_haml_scaffold/templates/blueprint/screen.css
- rails_generators/shoulda_haml_scaffold/templates/controller.rb
- rails_generators/shoulda_haml_scaffold/templates/functional_test.rb
- rails_generators/shoulda_haml_scaffold/templates/helper.rb
- rails_generators/shoulda_haml_scaffold/templates/layout.html.haml
- rails_generators/shoulda_haml_scaffold/templates/partial_form.html.haml
- rails_generators/shoulda_haml_scaffold/templates/view_edit.html.haml
- rails_generators/shoulda_haml_scaffold/templates/view_index.html.haml
- rails_generators/shoulda_haml_scaffold/templates/view_new.html.haml
- rails_generators/shoulda_haml_scaffold/templates/view_show.html.haml
- rails_generators/shoulda_haml_scaffold/USAGE
- rails_generators/shoulda_model/shoulda_model_generator.rb
- rails_generators/shoulda_model/templates/factory.rb
- rails_generators/shoulda_model/templates/fixtures.yml
- rails_generators/shoulda_model/templates/migration.rb
- rails_generators/shoulda_model/templates/model.rb
- rails_generators/shoulda_model/templates/unit_test.rb
- rails_generators/shoulda_model/USAGE
- Rakefile
- README.markdown
- shoulda-generators.gemspec
has_rdoc: true
homepage: http://github.com/technicalpickles/shoulda-generators
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Shoulda-generators
- --main
- README.markdown
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: shoulda-generators
rubygems_version: 1.2.0
specification_version: 2
summary: Generators which create tests using shoulda
test_files: []
